site_name: OneShot

repo_url: https://github.com/SBD1/2023.2-OneShot

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  language: pt-BR
  logo: images/favicon.ico
  favicon: images/favicon.ico
  font:
    text: Roboto


  palette: 
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  icon:
    repo: fontawesome/brands/github
    
  features:
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.indexes

nav:
  - Modelagem:
    - Modelagem: documentos/modelagem/index.md
    - Modelo Conceitual: documentos/modelagem/modelo-conceitual.md
    - Modelo Lógico: documentos/modelagem/modelo-logico.md
  - Modelo Físico:
    - Modelo Físico: documentos/modelo-fisico/index.md
    - Data Definition Language (DDL): documentos/modelo-fisico/ddl.md
    - Data Manipulation Language (DML): documentos/modelo-fisico/dml.md
    - Data Query Language (DQL): documentos/modelo-fisico/dql.md
    - Álgebra Relacional: documentos/modelo-fisico/algebra.md
  - Apresentações:
    - 1ª Apresentação: documentos/apresentacoes/modulo-1.md
    - 2ª Apresentação: documentos/apresentacoes/modulo-2.md